# Generated by Django 5.1.4 on 2024-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companyLogoUrl',
            field=models.URLField(default='', max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='details_url',
            field=models.URLField(max_length=5000),
        ),
    ]
